### ISSUE TITLE
Create new Component

### ISSUE THREAD

**Issue by dovecancode** [dovecancode/al-ameer#107]
Please do this

- [ ] 1. Create a component and named it <**PageHeader**> in components folder
- [ ] 2. Call <**Header**> and <**Navbar**> components inside <**PageHeader**>
  > 🗊 Note: <**Header**> and <**Navbar**> is inside App.jsx as of this moment. Remove it there including the <**Footer**>
- [ ] 3. Inside Screens Folder Call <**PageHeader**> in every component(index.jsx) on a top-level, same thing with <**Footer**> but call it on the bottom level
  >  🗊 Note:  Dont touch DashboardScreens

**Comment by HughOwenPanopio** [comment]
enhancement/#107-Create New Component: Working on it

**Comment by HughOwenPanopio** [comment]
enhancement/#107-PageHeader: Done on this task, however attempt failed on updating the vercel and cloud after merging the task on develop branch.
