### ISSUE TITLE
Under Construction UI

### ISSUE THREAD

**Issue by dovecancode** [dovecancode/al-ameer#111]
Please start working on under construction UI see the screenshot below

> The design is in the Figma file

This construction UI will be rendered to all pages that are currently in a development mode
Enjoy coding:😁

![Image](https://github.com/dovecancode/al-ameer/assets/142895411/c8e0206a-ed56-4557-b730-037a957f5a4c)

**Comment by HughOwenPanopio** [comment]
#111: Working on it

**Comment by HughOwenPanopio** [comment]
#111: ready for next task
