### ISSUE TITLE
[FEATURE] : Build the Login And Signup Page

### ISSUE THREAD

**Issue by dovecancode** [dovecancode/al-ameer#131]
Please start working on the login and signup page

1. [ ] Create routes for the Login and Sign Up page in App.jsx
2. [ ] Create screens for login and signup page > ``Sreens`` folder
3. [ ] Inside the src folder create a folder and name it ``features`` then inside it create a new folder again and name it ``authentication`` and from this folder create the login and signup form component
4. [ ] To simplify the process of handling forms in React applications we will be using a third-party package called [React Hook Form](https://react-hook-form.com/) 

Here are the screens for the login and signup page: 

![Image](https://github.com/dovecancode/al-ameer/assets/142895411/533e8ade-81fc-42cf-a72c-61a1a546ee93)

Please see the Figma design

Happy Coding!!! 😁

**Comment by HughOwenPanopio** [comment]
#131: Will be working on this, thank you.

**Comment by HughOwenPanopio** [comment]
close: #165
