### ISSUE TITLE
[ENHANCEMENT] README file

### ISSUE THREAD

**Issue by dovecancode** [dovecancode/al-ameer#170]
- [ ] Please add contributors the look and feel are something like in the screenshot below:

![Image](https://github.com/dovecancode/al-ameer/assets/142895411/71318ae1-60ad-49d7-b9da-82f88a97c60b)

**Comment by HughOwenPanopio** [comment]
#170: will work on this

**Comment by HughOwenPanopio** [comment]
#170: Done, created README file with avatars.
