### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by dovecancode** [dovecancode/al-ameer#20]
Please start working on the footer and make it responsive 

![image](https://github.com/dovecancode/al-ameer/assets/142895411/efe38569-4e08-4282-b014-095f6798c7cc)

**Comment by fahbwd80** [comment]
I'm working on it.

**Comment by dovecancode** [comment]
sir @fahbwd80 ako na titira neto hehehehe

**Comment by dovecancode** [comment]
Close #20
Nailed it
